
title: Resume - Jay Amgalan
url: 'http://jantsankhorloo.github.io'
baseurl:  #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Jay Amgalan
tagline: 
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: jamgalan@purdue.edu
phone: 765 490 4293
linkedin: jantsankhorloo-amgalan-878684113
github: jantsankhorloo

# Tracker
analytics: UA-105697187-1
#Update all the sections by editing the files inside _includes folder.
